[package]
name = "create_command"
version = "0.1.0"
authors = ["Charles <charles.capelli@qonfucius.team>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.14"
